/*
 * Opdex Platform API
 *
 * The Opdex Platform Web API is an interface for querying information from the Opdex contract indexer and quoting Opdex smart contract transactions. The Opdex contract indexer is a job that continually runs and stores relevant broadcast transaction data, in a way that represents the current known state of the Opdex protocol at the present time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opdex.Client.Api;
using Opdex.Client.Model;
using Opdex.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opdex.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CertificateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CertificateResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CertificateResponse
        //private CertificateResponse instance;

        public CertificateResponseTests()
        {
            // TODO uncomment below to create an instance of CertificateResponse
            //instance = new CertificateResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CertificateResponse
        /// </summary>
        [Fact]
        public void CertificateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CertificateResponse
            //Assert.IsType<CertificateResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'VestingStartBlock'
        /// </summary>
        [Fact]
        public void VestingStartBlockTest()
        {
            // TODO unit test for the property 'VestingStartBlock'
        }
        /// <summary>
        /// Test the property 'VestingEndBlock'
        /// </summary>
        [Fact]
        public void VestingEndBlockTest()
        {
            // TODO unit test for the property 'VestingEndBlock'
        }
        /// <summary>
        /// Test the property 'Redeemed'
        /// </summary>
        [Fact]
        public void RedeemedTest()
        {
            // TODO unit test for the property 'Redeemed'
        }
        /// <summary>
        /// Test the property 'Revoked'
        /// </summary>
        [Fact]
        public void RevokedTest()
        {
            // TODO unit test for the property 'Revoked'
        }
        /// <summary>
        /// Test the property 'Proposals'
        /// </summary>
        [Fact]
        public void ProposalsTest()
        {
            // TODO unit test for the property 'Proposals'
        }

    }

}
