/*
 * Opdex Platform API
 *
 * The Opdex Platform Web API is an interface for querying information from the Opdex contract indexer and quoting Opdex smart contract transactions. The Opdex contract indexer is a job that continually runs and stores relevant broadcast transaction data, in a way that represents the current known state of the Opdex protocol at the present time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opdex.Client.Api;
using Opdex.Client.Model;
using Opdex.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opdex.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CreateLiquidityPoolEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateLiquidityPoolEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateLiquidityPoolEvent
        //private CreateLiquidityPoolEvent instance;

        public CreateLiquidityPoolEventTests()
        {
            // TODO uncomment below to create an instance of CreateLiquidityPoolEvent
            //instance = new CreateLiquidityPoolEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateLiquidityPoolEvent
        /// </summary>
        [Fact]
        public void CreateLiquidityPoolEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateLiquidityPoolEvent
            //Assert.IsType<CreateLiquidityPoolEvent>(instance);
        }


        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'LiquidityPool'
        /// </summary>
        [Fact]
        public void LiquidityPoolTest()
        {
            // TODO unit test for the property 'LiquidityPool'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }
        /// <summary>
        /// Test the property 'Contract'
        /// </summary>
        [Fact]
        public void ContractTest()
        {
            // TODO unit test for the property 'Contract'
        }
        /// <summary>
        /// Test the property 'SortOrder'
        /// </summary>
        [Fact]
        public void SortOrderTest()
        {
            // TODO unit test for the property 'SortOrder'
        }

    }

}
