/*
 * Opdex Platform API
 *
 * The Opdex Platform Web API is an interface for querying information from the Opdex contract indexer and quoting Opdex smart contract transactions. The Opdex contract indexer is a job that continually runs and stores relevant broadcast transaction data, in a way that represents the current known state of the Opdex protocol at the present time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opdex.Client.Api;
using Opdex.Client.Model;
using Opdex.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opdex.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DistributionEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DistributionEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DistributionEvent
        //private DistributionEvent instance;

        public DistributionEventTests()
        {
            // TODO uncomment below to create an instance of DistributionEvent
            //instance = new DistributionEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DistributionEvent
        /// </summary>
        [Fact]
        public void DistributionEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" DistributionEvent
            //Assert.IsType<DistributionEvent>(instance);
        }


        /// <summary>
        /// Test the property 'VaultAmount'
        /// </summary>
        [Fact]
        public void VaultAmountTest()
        {
            // TODO unit test for the property 'VaultAmount'
        }
        /// <summary>
        /// Test the property 'MiningGovernanceAmount'
        /// </summary>
        [Fact]
        public void MiningGovernanceAmountTest()
        {
            // TODO unit test for the property 'MiningGovernanceAmount'
        }
        /// <summary>
        /// Test the property 'PeriodIndex'
        /// </summary>
        [Fact]
        public void PeriodIndexTest()
        {
            // TODO unit test for the property 'PeriodIndex'
        }
        /// <summary>
        /// Test the property 'TotalSupply'
        /// </summary>
        [Fact]
        public void TotalSupplyTest()
        {
            // TODO unit test for the property 'TotalSupply'
        }
        /// <summary>
        /// Test the property 'NextDistributionBlock'
        /// </summary>
        [Fact]
        public void NextDistributionBlockTest()
        {
            // TODO unit test for the property 'NextDistributionBlock'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }
        /// <summary>
        /// Test the property 'Contract'
        /// </summary>
        [Fact]
        public void ContractTest()
        {
            // TODO unit test for the property 'Contract'
        }
        /// <summary>
        /// Test the property 'SortOrder'
        /// </summary>
        [Fact]
        public void SortOrderTest()
        {
            // TODO unit test for the property 'SortOrder'
        }

    }

}
