/*
 * Opdex Platform API
 *
 * The Opdex Platform Web API is an interface for querying information from the Opdex contract indexer and quoting Opdex smart contract transactions. The Opdex contract indexer is a job that continually runs and stores relevant broadcast transaction data, in a way that represents the current known state of the Opdex protocol at the present time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opdex.Client.Api;
using Opdex.Client.Model;
using Opdex.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opdex.Client.Test.Model
{
    /// <summary>
    ///  Class for testing MiningGovernanceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MiningGovernanceResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MiningGovernanceResponse
        //private MiningGovernanceResponse instance;

        public MiningGovernanceResponseTests()
        {
            // TODO uncomment below to create an instance of MiningGovernanceResponse
            //instance = new MiningGovernanceResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MiningGovernanceResponse
        /// </summary>
        [Fact]
        public void MiningGovernanceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" MiningGovernanceResponse
            //Assert.IsType<MiningGovernanceResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'PeriodEndBlock'
        /// </summary>
        [Fact]
        public void PeriodEndBlockTest()
        {
            // TODO unit test for the property 'PeriodEndBlock'
        }
        /// <summary>
        /// Test the property 'PeriodRemainingBlocks'
        /// </summary>
        [Fact]
        public void PeriodRemainingBlocksTest()
        {
            // TODO unit test for the property 'PeriodRemainingBlocks'
        }
        /// <summary>
        /// Test the property 'PeriodBlockDuration'
        /// </summary>
        [Fact]
        public void PeriodBlockDurationTest()
        {
            // TODO unit test for the property 'PeriodBlockDuration'
        }
        /// <summary>
        /// Test the property 'PeriodsUntilRewardReset'
        /// </summary>
        [Fact]
        public void PeriodsUntilRewardResetTest()
        {
            // TODO unit test for the property 'PeriodsUntilRewardReset'
        }
        /// <summary>
        /// Test the property 'MiningPoolRewardPerPeriod'
        /// </summary>
        [Fact]
        public void MiningPoolRewardPerPeriodTest()
        {
            // TODO unit test for the property 'MiningPoolRewardPerPeriod'
        }
        /// <summary>
        /// Test the property 'TotalRewardsPerPeriod'
        /// </summary>
        [Fact]
        public void TotalRewardsPerPeriodTest()
        {
            // TODO unit test for the property 'TotalRewardsPerPeriod'
        }
        /// <summary>
        /// Test the property 'MinedToken'
        /// </summary>
        [Fact]
        public void MinedTokenTest()
        {
            // TODO unit test for the property 'MinedToken'
        }

    }

}
