/*
 * Opdex Platform API
 *
 * The Opdex Platform Web API is an interface for querying information from the Opdex contract indexer and quoting Opdex smart contract transactions. The Opdex contract indexer is a job that continually runs and stores relevant broadcast transaction data, in a way that represents the current known state of the Opdex protocol at the present time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opdex.Client.Api;
using Opdex.Client.Model;
using Opdex.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opdex.Client.Test.Model
{
    /// <summary>
    ///  Class for testing OhlcFixedDecimalResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OhlcFixedDecimalResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OhlcFixedDecimalResponse
        //private OhlcFixedDecimalResponse instance;

        public OhlcFixedDecimalResponseTests()
        {
            // TODO uncomment below to create an instance of OhlcFixedDecimalResponse
            //instance = new OhlcFixedDecimalResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OhlcFixedDecimalResponse
        /// </summary>
        [Fact]
        public void OhlcFixedDecimalResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" OhlcFixedDecimalResponse
            //Assert.IsType<OhlcFixedDecimalResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Open'
        /// </summary>
        [Fact]
        public void OpenTest()
        {
            // TODO unit test for the property 'Open'
        }
        /// <summary>
        /// Test the property 'High'
        /// </summary>
        [Fact]
        public void HighTest()
        {
            // TODO unit test for the property 'High'
        }
        /// <summary>
        /// Test the property 'Low'
        /// </summary>
        [Fact]
        public void LowTest()
        {
            // TODO unit test for the property 'Low'
        }
        /// <summary>
        /// Test the property 'Close'
        /// </summary>
        [Fact]
        public void CloseTest()
        {
            // TODO unit test for the property 'Close'
        }

    }

}
