/*
 * Opdex Platform API
 *
 * The Opdex Platform Web API is an interface for querying information from the Opdex contract indexer and quoting Opdex smart contract transactions. The Opdex contract indexer is a job that continually runs and stores relevant broadcast transaction data, in a way that represents the current known state of the Opdex protocol at the present time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opdex.Client.Api;
using Opdex.Client.Model;
using Opdex.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opdex.Client.Test.Model
{
    /// <summary>
    ///  Class for testing StartMiningEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StartMiningEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StartMiningEvent
        //private StartMiningEvent instance;

        public StartMiningEventTests()
        {
            // TODO uncomment below to create an instance of StartMiningEvent
            //instance = new StartMiningEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StartMiningEvent
        /// </summary>
        [Fact]
        public void StartMiningEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" StartMiningEvent
            //Assert.IsType<StartMiningEvent>(instance);
        }


        /// <summary>
        /// Test the property 'Staker'
        /// </summary>
        [Fact]
        public void StakerTest()
        {
            // TODO unit test for the property 'Staker'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'MinerBalance'
        /// </summary>
        [Fact]
        public void MinerBalanceTest()
        {
            // TODO unit test for the property 'MinerBalance'
        }
        /// <summary>
        /// Test the property 'TotalSupply'
        /// </summary>
        [Fact]
        public void TotalSupplyTest()
        {
            // TODO unit test for the property 'TotalSupply'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }
        /// <summary>
        /// Test the property 'Contract'
        /// </summary>
        [Fact]
        public void ContractTest()
        {
            // TODO unit test for the property 'Contract'
        }
        /// <summary>
        /// Test the property 'SortOrder'
        /// </summary>
        [Fact]
        public void SortOrderTest()
        {
            // TODO unit test for the property 'SortOrder'
        }

    }

}
