/*
 * Opdex Platform API
 *
 * The Opdex Platform Web API is an interface for querying information from the Opdex contract indexer and quoting Opdex smart contract transactions. The Opdex contract indexer is a job that continually runs and stores relevant broadcast transaction data, in a way that represents the current known state of the Opdex protocol at the present time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opdex.Client.Api;
using Opdex.Client.Model;
using Opdex.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opdex.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TokenSummaryResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenSummaryResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokenSummaryResponse
        //private TokenSummaryResponse instance;

        public TokenSummaryResponseTests()
        {
            // TODO uncomment below to create an instance of TokenSummaryResponse
            //instance = new TokenSummaryResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenSummaryResponse
        /// </summary>
        [Fact]
        public void TokenSummaryResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokenSummaryResponse
            //Assert.IsType<TokenSummaryResponse>(instance);
        }


        /// <summary>
        /// Test the property 'PriceUsd'
        /// </summary>
        [Fact]
        public void PriceUsdTest()
        {
            // TODO unit test for the property 'PriceUsd'
        }
        /// <summary>
        /// Test the property 'DailyPriceChangePercent'
        /// </summary>
        [Fact]
        public void DailyPriceChangePercentTest()
        {
            // TODO unit test for the property 'DailyPriceChangePercent'
        }
        /// <summary>
        /// Test the property 'ModifiedBlock'
        /// </summary>
        [Fact]
        public void ModifiedBlockTest()
        {
            // TODO unit test for the property 'ModifiedBlock'
        }

    }

}
