/*
 * Opdex Platform API
 *
 * The Opdex Platform Web API is an interface for querying information from the Opdex contract indexer and quoting Opdex smart contract transactions. The Opdex contract indexer is a job that continually runs and stores relevant broadcast transaction data, in a way that represents the current known state of the Opdex protocol at the present time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Opdex.Client.Api;
using Opdex.Client.Model;
using Opdex.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Opdex.Client.Test.Model
{
    /// <summary>
    ///  Class for testing WrappedTokenDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WrappedTokenDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WrappedTokenDetails
        //private WrappedTokenDetails instance;

        public WrappedTokenDetailsTests()
        {
            // TODO uncomment below to create an instance of WrappedTokenDetails
            //instance = new WrappedTokenDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WrappedTokenDetails
        /// </summary>
        [Fact]
        public void WrappedTokenDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" WrappedTokenDetails
            //Assert.IsType<WrappedTokenDetails>(instance);
        }


        /// <summary>
        /// Test the property 'Custodian'
        /// </summary>
        [Fact]
        public void CustodianTest()
        {
            // TODO unit test for the property 'Custodian'
        }
        /// <summary>
        /// Test the property 'Chain'
        /// </summary>
        [Fact]
        public void ChainTest()
        {
            // TODO unit test for the property 'Chain'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Trusted'
        /// </summary>
        [Fact]
        public void TrustedTest()
        {
            // TODO unit test for the property 'Trusted'
        }
        /// <summary>
        /// Test the property 'Validated'
        /// </summary>
        [Fact]
        public void ValidatedTest()
        {
            // TODO unit test for the property 'Validated'
        }
        /// <summary>
        /// Test the property 'CreatedBlock'
        /// </summary>
        [Fact]
        public void CreatedBlockTest()
        {
            // TODO unit test for the property 'CreatedBlock'
        }
        /// <summary>
        /// Test the property 'ModifiedBlock'
        /// </summary>
        [Fact]
        public void ModifiedBlockTest()
        {
            // TODO unit test for the property 'ModifiedBlock'
        }

    }

}
