/*
 * Opdex Platform API
 *
 * The Opdex Platform Web API is an interface for querying information from the Opdex contract indexer and quoting Opdex smart contract transactions. The Opdex contract indexer is a job that continually runs and stores relevant broadcast transaction data, in a way that represents the current known state of the Opdex protocol at the present time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Opdex.Client.Client.FileParameter;
using OpenAPIDateConverter = Opdex.Client.Client.OpenAPIDateConverter;

namespace Opdex.Client.Model
{
    /// <summary>
    /// Request detailing desired liquidity deposit
    /// </summary>
    [DataContract(Name = "liquidityAmountInQuoteRequest")]
    public partial class LiquidityAmountInQuoteRequest : IEquatable<LiquidityAmountInQuoteRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LiquidityAmountInQuoteRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LiquidityAmountInQuoteRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LiquidityAmountInQuoteRequest" /> class.
        /// </summary>
        /// <param name="amountIn">Decimal value with uncapped precision and size (required).</param>
        /// <param name="tokenIn">tokenIn (required).</param>
        public LiquidityAmountInQuoteRequest(string amountIn = default(string), TokenAddress tokenIn = default(TokenAddress))
        {
            // to ensure "amountIn" is required (not null)
            if (amountIn == null) {
                throw new ArgumentNullException("amountIn is a required property for LiquidityAmountInQuoteRequest and cannot be null");
            }
            this.AmountIn = amountIn;
            // to ensure "tokenIn" is required (not null)
            if (tokenIn == null) {
                throw new ArgumentNullException("tokenIn is a required property for LiquidityAmountInQuoteRequest and cannot be null");
            }
            this.TokenIn = tokenIn;
        }

        /// <summary>
        /// Decimal value with uncapped precision and size
        /// </summary>
        /// <value>Decimal value with uncapped precision and size</value>
        [DataMember(Name = "amountIn", IsRequired = true, EmitDefaultValue = false)]
        public string AmountIn { get; set; }

        /// <summary>
        /// Gets or Sets TokenIn
        /// </summary>
        [DataMember(Name = "tokenIn", IsRequired = true, EmitDefaultValue = false)]
        public TokenAddress TokenIn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LiquidityAmountInQuoteRequest {\n");
            sb.Append("  AmountIn: ").Append(AmountIn).Append("\n");
            sb.Append("  TokenIn: ").Append(TokenIn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LiquidityAmountInQuoteRequest);
        }

        /// <summary>
        /// Returns true if LiquidityAmountInQuoteRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of LiquidityAmountInQuoteRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LiquidityAmountInQuoteRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AmountIn == input.AmountIn ||
                    (this.AmountIn != null &&
                    this.AmountIn.Equals(input.AmountIn))
                ) && 
                (
                    this.TokenIn == input.TokenIn ||
                    (this.TokenIn != null &&
                    this.TokenIn.Equals(input.TokenIn))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AmountIn != null)
                {
                    hashCode = (hashCode * 59) + this.AmountIn.GetHashCode();
                }
                if (this.TokenIn != null)
                {
                    hashCode = (hashCode * 59) + this.TokenIn.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // AmountIn (string) pattern
            Regex regexAmountIn = new Regex(@"^\\d*\\.\\d{1,18}$", RegexOptions.CultureInvariant);
            if (false == regexAmountIn.Match(this.AmountIn).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for AmountIn, must match a pattern of " + regexAmountIn, new [] { "AmountIn" });
            }

            yield break;
        }
    }

}
