/*
 * Opdex Platform API
 *
 * The Opdex Platform Web API is an interface for querying information from the Opdex contract indexer and quoting Opdex smart contract transactions. The Opdex contract indexer is a job that continually runs and stores relevant broadcast transaction data, in a way that represents the current known state of the Opdex protocol at the present time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Opdex.Client.Client.FileParameter;
using OpenAPIDateConverter = Opdex.Client.Client.OpenAPIDateConverter;

namespace Opdex.Client.Model
{
    /// <summary>
    /// Property to sort markets by
    /// </summary>
    /// <value>Property to sort markets by</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MarketOrderByType
    {
        /// <summary>
        /// Enum CreatedBlock for value: CreatedBlock
        /// </summary>
        [EnumMember(Value = "CreatedBlock")]
        CreatedBlock = 1,

        /// <summary>
        /// Enum LiquidityUsd for value: LiquidityUsd
        /// </summary>
        [EnumMember(Value = "LiquidityUsd")]
        LiquidityUsd = 2,

        /// <summary>
        /// Enum StakingUsd for value: StakingUsd
        /// </summary>
        [EnumMember(Value = "StakingUsd")]
        StakingUsd = 3,

        /// <summary>
        /// Enum StakingWeight for value: StakingWeight
        /// </summary>
        [EnumMember(Value = "StakingWeight")]
        StakingWeight = 4,

        /// <summary>
        /// Enum VolumeUsd for value: VolumeUsd
        /// </summary>
        [EnumMember(Value = "VolumeUsd")]
        VolumeUsd = 5,

        /// <summary>
        /// Enum MarketRewardsDailyUsd for value: MarketRewardsDailyUsd
        /// </summary>
        [EnumMember(Value = "MarketRewardsDailyUsd")]
        MarketRewardsDailyUsd = 6,

        /// <summary>
        /// Enum ProviderRewardsDailyUsd for value: ProviderRewardsDailyUsd
        /// </summary>
        [EnumMember(Value = "ProviderRewardsDailyUsd")]
        ProviderRewardsDailyUsd = 7,

        /// <summary>
        /// Enum DailyLiquidityUsdChangePercent for value: DailyLiquidityUsdChangePercent
        /// </summary>
        [EnumMember(Value = "DailyLiquidityUsdChangePercent")]
        DailyLiquidityUsdChangePercent = 8,

        /// <summary>
        /// Enum DailyStakingUsdChangePercent for value: DailyStakingUsdChangePercent
        /// </summary>
        [EnumMember(Value = "DailyStakingUsdChangePercent")]
        DailyStakingUsdChangePercent = 9,

        /// <summary>
        /// Enum DailyStakingWeightChangePercent for value: DailyStakingWeightChangePercent
        /// </summary>
        [EnumMember(Value = "DailyStakingWeightChangePercent")]
        DailyStakingWeightChangePercent = 10

    }

}
