/*
 * Opdex Platform API
 *
 * The Opdex Platform Web API is an interface for querying information from the Opdex contract indexer and quoting Opdex smart contract transactions. The Opdex contract indexer is a job that continually runs and stores relevant broadcast transaction data, in a way that represents the current known state of the Opdex protocol at the present time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Opdex.Client.Client.OpenAPIDateConverter;

namespace Opdex.Client.Model
{
    /// <summary>
    /// RewardSummary
    /// </summary>
    [DataContract(Name = "rewardSummary")]
    public partial class RewardSummary : IEquatable<RewardSummary>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RewardSummary" /> class.
        /// </summary>
        /// <param name="providerDailyUsd">USD value of rewards distributed to liquidity providers for the day.</param>
        /// <param name="marketDailyUsd">USD value of rewards distributed to the market for the day.</param>
        /// <param name="totalDailyUsd">Total USD value of rewards distributed for the day.</param>
        public RewardSummary(decimal providerDailyUsd = default(decimal), decimal marketDailyUsd = default(decimal), decimal totalDailyUsd = default(decimal))
        {
            this.ProviderDailyUsd = providerDailyUsd;
            this.MarketDailyUsd = marketDailyUsd;
            this.TotalDailyUsd = totalDailyUsd;
        }

        /// <summary>
        /// USD value of rewards distributed to liquidity providers for the day
        /// </summary>
        /// <value>USD value of rewards distributed to liquidity providers for the day</value>
        [DataMember(Name = "providerDailyUsd", EmitDefaultValue = false)]
        public decimal ProviderDailyUsd { get; set; }

        /// <summary>
        /// USD value of rewards distributed to the market for the day
        /// </summary>
        /// <value>USD value of rewards distributed to the market for the day</value>
        [DataMember(Name = "marketDailyUsd", EmitDefaultValue = false)]
        public decimal MarketDailyUsd { get; set; }

        /// <summary>
        /// Total USD value of rewards distributed for the day
        /// </summary>
        /// <value>Total USD value of rewards distributed for the day</value>
        [DataMember(Name = "totalDailyUsd", EmitDefaultValue = false)]
        public decimal TotalDailyUsd { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RewardSummary {\n");
            sb.Append("  ProviderDailyUsd: ").Append(ProviderDailyUsd).Append("\n");
            sb.Append("  MarketDailyUsd: ").Append(MarketDailyUsd).Append("\n");
            sb.Append("  TotalDailyUsd: ").Append(TotalDailyUsd).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RewardSummary);
        }

        /// <summary>
        /// Returns true if RewardSummary instances are equal
        /// </summary>
        /// <param name="input">Instance of RewardSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RewardSummary input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ProviderDailyUsd == input.ProviderDailyUsd ||
                    this.ProviderDailyUsd.Equals(input.ProviderDailyUsd)
                ) && 
                (
                    this.MarketDailyUsd == input.MarketDailyUsd ||
                    this.MarketDailyUsd.Equals(input.MarketDailyUsd)
                ) && 
                (
                    this.TotalDailyUsd == input.TotalDailyUsd ||
                    this.TotalDailyUsd.Equals(input.TotalDailyUsd)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.ProviderDailyUsd.GetHashCode();
                hashCode = (hashCode * 59) + this.MarketDailyUsd.GetHashCode();
                hashCode = (hashCode * 59) + this.TotalDailyUsd.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // ProviderDailyUsd (decimal) minimum
            if (this.ProviderDailyUsd < (decimal)0.0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ProviderDailyUsd, must be a value greater than or equal to 0.0.", new [] { "ProviderDailyUsd" });
            }

            // MarketDailyUsd (decimal) minimum
            if (this.MarketDailyUsd < (decimal)0.0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MarketDailyUsd, must be a value greater than or equal to 0.0.", new [] { "MarketDailyUsd" });
            }

            // TotalDailyUsd (decimal) minimum
            if (this.TotalDailyUsd < (decimal)0.0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TotalDailyUsd, must be a value greater than or equal to 0.0.", new [] { "TotalDailyUsd" });
            }

            yield break;
        }
    }

}
