/*
 * Opdex Platform API
 *
 * The Opdex Platform Web API is an interface for querying information from the Opdex contract indexer and quoting Opdex smart contract transactions. The Opdex contract indexer is a job that continually runs and stores relevant broadcast transaction data, in a way that represents the current known state of the Opdex protocol at the present time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Opdex.Client.Client.FileParameter;
using OpenAPIDateConverter = Opdex.Client.Client.OpenAPIDateConverter;

namespace Opdex.Client.Model
{
    /// <summary>
    /// Attribute that can be applied to a token
    /// </summary>
    /// <value>Attribute that can be applied to a token</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TokenAttribute
    {
        /// <summary>
        /// Enum Provisional for value: Provisional
        /// </summary>
        [EnumMember(Value = "Provisional")]
        Provisional = 1,

        /// <summary>
        /// Enum NonProvisional for value: NonProvisional
        /// </summary>
        [EnumMember(Value = "NonProvisional")]
        NonProvisional = 2,

        /// <summary>
        /// Enum Staking for value: Staking
        /// </summary>
        [EnumMember(Value = "Staking")]
        Staking = 3,

        /// <summary>
        /// Enum Security for value: Security
        /// </summary>
        [EnumMember(Value = "Security")]
        Security = 4

    }

}
