/*
 * Opdex Platform API
 *
 * The Opdex Platform Web API is an interface for querying information from the Opdex contract indexer and quoting Opdex smart contract transactions. The Opdex contract indexer is a job that continually runs and stores relevant broadcast transaction data, in a way that represents the current known state of the Opdex protocol at the present time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Opdex.Client.Client.FileParameter;
using OpenAPIDateConverter = Opdex.Client.Client.OpenAPIDateConverter;

namespace Opdex.Client.Model
{
    /// <summary>
    /// VolumeSummary
    /// </summary>
    [DataContract(Name = "volumeSummary")]
    public partial class VolumeSummary : IEquatable<VolumeSummary>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VolumeSummary" /> class.
        /// </summary>
        /// <param name="dailyUsd">USD value of total daily volume.</param>
        public VolumeSummary(decimal dailyUsd = default(decimal))
        {
            this.DailyUsd = dailyUsd;
        }

        /// <summary>
        /// USD value of total daily volume
        /// </summary>
        /// <value>USD value of total daily volume</value>
        [DataMember(Name = "dailyUsd", EmitDefaultValue = false)]
        public decimal DailyUsd { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VolumeSummary {\n");
            sb.Append("  DailyUsd: ").Append(DailyUsd).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VolumeSummary);
        }

        /// <summary>
        /// Returns true if VolumeSummary instances are equal
        /// </summary>
        /// <param name="input">Instance of VolumeSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VolumeSummary input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.DailyUsd == input.DailyUsd ||
                    this.DailyUsd.Equals(input.DailyUsd)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.DailyUsd.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // DailyUsd (decimal) minimum
            if (this.DailyUsd < (decimal)0.0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DailyUsd, must be a value greater than or equal to 0.0.", new [] { "DailyUsd" });
            }

            yield break;
        }
    }

}
